#[macro_use]
extern crate objc;

pub mod app_bundle;
pub mod audio;
pub mod canonical;
pub mod cef_bridge;
pub mod cli;
pub mod cpu;
pub mod d3d12;
pub mod d3d11;
pub mod diagnostics;
pub mod error;
pub mod ge;
pub mod gfx;
pub mod guest_support;
pub mod icon;
pub mod installer;
pub mod jit;
pub mod live;
pub mod metal_backend;
pub mod metal_renderer;
pub mod logging;
pub mod media;
pub mod midi;
pub mod network;
pub mod oracle_model;
pub mod pe;
pub mod pe_runtime;
pub mod gdiplus_render;
pub mod perf;
pub mod real_audio;
pub mod real_fs;
pub mod real_hid;
pub mod real_net;
pub mod real_win32;
pub mod reason;
pub mod runner;
pub mod scm;
pub mod seh;
pub mod security;
pub mod shader;
pub mod shader_compiler;
pub mod steam;
pub mod steam_integration;
pub mod steam_protocol;
pub mod telemetry;
pub mod threads;
pub mod trace;
pub mod user32;
pub mod util;
pub mod video_decoder;
pub mod vkgl;
pub mod steam_input;
pub mod steamvr;
pub mod wmi;
pub mod win32;
pub mod winhttp;
pub mod wininet;
pub mod dwrite;
pub mod d2d;
pub mod print;
pub mod webview2;
pub mod winmm;

pub const PRODUCT_NAME: &str = "Casa1";
pub const CLI_NAME: &str = "macwin";
pub const BUILD_ID: &str = concat!("casa1-", env!("CARGO_PKG_VERSION"));
pub const TRACE_FORMAT_VERSION: u32 = 1;
pub const TRACE_CACHE_VERSION: u32 = 1;