pub mod audio;
pub mod canonical;
pub mod cli;
pub mod cpu;
pub mod d3d12;
pub mod d3d11;
pub mod diagnostics;
pub mod error;
pub mod ge;
pub mod gfx;
pub mod guest_support;
pub mod installer;
pub mod live;
pub mod logging;
pub mod media;
pub mod network;
pub mod oracle_model;
pub mod pe;
pub mod pe_runtime;
pub mod reason;
pub mod runner;
pub mod security;
pub mod shader;
pub mod steam;
pub mod trace;
pub mod user32;
pub mod util;
pub mod vkgl;
pub mod win32;

pub const PRODUCT_NAME: &str = "Casa1";
pub const CLI_NAME: &str = "macwin";
pub const BUILD_ID: &str = concat!("casa1-", env!("CARGO_PKG_VERSION"));
pub const TRACE_FORMAT_VERSION: u32 = 1;
pub const TRACE_CACHE_VERSION: u32 = 1;