use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum ReasonCode {
    Success = 0,
    RcCliInvalid = 1000,
    RcGeExists = 1001,
    RcGeNotFound = 1002,
    RcIo = 1003,
    RcRunnerSpawnFailed = 1004,
    RcRunnerProtocolInvalid = 1005,
    RcTraceEnvMismatch = 1006,
    RcCompareMismatch = 1007,
    RcDiagnosticsExportFailed = 1008,
    RcHelperPermissionDenied = 1009,
    RcEntitlementAuditFailed = 1010,
    RcEntitlementValidationError = 1011,
    RcFsPathInvalid = 1100,
    RcFsAlreadyExists = 1101,
    RcFsNotFound = 1102,
    RcFsReservedName = 1103,
    RcFsPathTooLong = 1104,
    RcFsSharingViolation = 1105,
    RcFsLockViolation = 1106,
    RcFsSandboxEscape = 1107,
    RcSandboxPathViolation = 1108,
    RcRegistryNotFound = 1200,
    RcWin32InvalidHandle = 1300,
    RcWin32Timeout = 1301,
    RcComClassNotRegistered = 1302,
    RcMemoryAccessViolation = 1303,
    RcPipeBusy = 1304,
    RcWin32NotOwner = 1310,
    RcComObjectError = 1305,
    RcHandleStaleOrInvalid = 1306,
    RcPeParseInvalid = 2000,
    RcImportMissing = 2001,
    RcUnimplInsn = 2002,
    RcD3dFeatureUnsupported = 2003,
    RcAnticheatDriverDetected = 2004,
    RcTlsCertRejected = 2005,
    RcMsiCustomActionServiceBlocked = 2006,
    RcTlsValidationFailed = 2007,
    RcBufferLimitExceeded = 2008,
    RcInvalidGuestEnum = 2009,
    RcJitCodeAllocFailed = 2010,
    RcParserTruncation = 2011,
    RcUnsupportedPlatform = 2012,
    RcTlsCertificatePinMismatch = 2013,
    RcUnsupportedPlatformApi = 2014,
    RcParserTruncated = 2015,
    RcJitCompilationError = 2016,
    RcExecutableMemoryExhausted = 2017,
    RcGuestPointerOutOfRange = 2018,
    RcGuestStringInvalid = 2019,
    RcInputUnsupported = 2100,
    RcDxilInvalid = 2101,
    RcDxilBindingAmbiguous = 2102,
    RcCacheCorrupt = 2103,
    RcD3dInvalidState = 2104,
    RcD3d9NotSupported = 2105,
    RcVulkanNotSupported = 2106,
    RcOpenGlNotSupported = 2107,
    RcInvalidState = 2108,
    RcNotFound = 2109,
    RcAudioUnsupported = 2200,
    RcAudioBufferSizeMismatch = 2201,
    RcWinsockWouldBlock = 2300,
    RcDnsNotFound = 2301,
    RcCryptoInvalid = 2302,
    RcDotnetUnsupported = 2400,
    RcSteamUpdateFailed = 2500,
    RcMediaInvalid = 2600,
    RcNetworkUnreachable = 2700,
    RcNetworkProtocolInvalid = 2701,
    RcMsiInvalid = 2702,
    RcNetDnsResolutionFailed = 2703,
    RcNetConnectionFailed = 2704,
    RcNetWriteFailed = 2705,
    RcNetReadFailed = 2706,
    RcNetProtocolError = 2707,
    RcNetHttpRequestFailed = 2708,
    RcNetHttpHeaderNotFound = 2709,
    RcNetSocketCreateFailed = 2710,
    RcNetSendFailed = 2711,
    RcWebSocketFrameTooLarge = 2712,
    RcHttpHeaderLimitExceeded = 2713,
    RcPortParseError = 2714,
    RcRequestBodyTooLarge = 2715,
    RcSocketReceiveQueueFull = 2716,
    RcDrmInitFailed = 2800,
    RcDrmDecryptFailed = 2801,
    RcDrmIntegrityFailed = 2802,
    RcDrmLicenseInvalid = 2803,
    RcDrmPackUnsupported = 2804,
    RcDrmSectionNotFound = 2805,
    RcDrmRegionNotFound = 2806,
    RcWmiParseError = 2900,
    RcWmiClassNotFound = 2901,
    RcWmiObjectNotFound = 2902,
    RcTelemetryRanking = 2903,
    SehException = 3000,
    VeHandlerUnhandled = 3001,
    RcCrashRecoveryError = 3002,
    Halted = 3102,
    RcSignalHandlerError = 3103,
    RcInvalidParameter = 3100,
    RcOutOfMemory = 3200,
    RcOutOfMemoryHint = 3201,
    RcLockPoisoned = 3300,
}

impl ReasonCode {
    pub const fn as_u32(self) -> u32 {
        self as u32
    }

    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Success),
            1000 => Some(Self::RcCliInvalid),
            1001 => Some(Self::RcGeExists),
            1002 => Some(Self::RcGeNotFound),
            1003 => Some(Self::RcIo),
            1004 => Some(Self::RcRunnerSpawnFailed),
            1005 => Some(Self::RcRunnerProtocolInvalid),
            1006 => Some(Self::RcTraceEnvMismatch),
            1007 => Some(Self::RcCompareMismatch),
            1008 => Some(Self::RcDiagnosticsExportFailed),
            1009 => Some(Self::RcHelperPermissionDenied),
            1010 => Some(Self::RcEntitlementAuditFailed),
            1011 => Some(Self::RcEntitlementValidationError),
            1100 => Some(Self::RcFsPathInvalid),
            1101 => Some(Self::RcFsAlreadyExists),
            1102 => Some(Self::RcFsNotFound),
            1103 => Some(Self::RcFsReservedName),
            1104 => Some(Self::RcFsPathTooLong),
            1105 => Some(Self::RcFsSharingViolation),
            1106 => Some(Self::RcFsLockViolation),
            1107 => Some(Self::RcFsSandboxEscape),
            1108 => Some(Self::RcSandboxPathViolation),
            1200 => Some(Self::RcRegistryNotFound),
            1300 => Some(Self::RcWin32InvalidHandle),
            1301 => Some(Self::RcWin32Timeout),
            1302 => Some(Self::RcComClassNotRegistered),
            1303 => Some(Self::RcMemoryAccessViolation),
            1304 => Some(Self::RcPipeBusy),
            1310 => Some(Self::RcWin32NotOwner),
            1305 => Some(Self::RcComObjectError),
            1306 => Some(Self::RcHandleStaleOrInvalid),
            2000 => Some(Self::RcPeParseInvalid),
            2001 => Some(Self::RcImportMissing),
            2002 => Some(Self::RcUnimplInsn),
            2003 => Some(Self::RcD3dFeatureUnsupported),
            2004 => Some(Self::RcAnticheatDriverDetected),
            2005 => Some(Self::RcTlsCertRejected),
            2006 => Some(Self::RcMsiCustomActionServiceBlocked),
            2007 => Some(Self::RcTlsValidationFailed),
            2008 => Some(Self::RcBufferLimitExceeded),
            2009 => Some(Self::RcInvalidGuestEnum),
            2010 => Some(Self::RcJitCodeAllocFailed),
            2011 => Some(Self::RcParserTruncation),
            2012 => Some(Self::RcUnsupportedPlatform),
            2013 => Some(Self::RcTlsCertificatePinMismatch),
            2014 => Some(Self::RcUnsupportedPlatformApi),
            2015 => Some(Self::RcParserTruncated),
            2016 => Some(Self::RcJitCompilationError),
            2017 => Some(Self::RcExecutableMemoryExhausted),
            2018 => Some(Self::RcGuestPointerOutOfRange),
            2019 => Some(Self::RcGuestStringInvalid),
            2100 => Some(Self::RcInputUnsupported),
            2101 => Some(Self::RcDxilInvalid),
            2102 => Some(Self::RcDxilBindingAmbiguous),
            2103 => Some(Self::RcCacheCorrupt),
            2104 => Some(Self::RcD3dInvalidState),
            2105 => Some(Self::RcD3d9NotSupported),
            2106 => Some(Self::RcVulkanNotSupported),
            2107 => Some(Self::RcOpenGlNotSupported),
            2108 => Some(Self::RcInvalidState),
            2109 => Some(Self::RcNotFound),
            2200 => Some(Self::RcAudioUnsupported),
            2201 => Some(Self::RcAudioBufferSizeMismatch),
            2300 => Some(Self::RcWinsockWouldBlock),
            2301 => Some(Self::RcDnsNotFound),
            2302 => Some(Self::RcCryptoInvalid),
            2400 => Some(Self::RcDotnetUnsupported),
            2500 => Some(Self::RcSteamUpdateFailed),
            2600 => Some(Self::RcMediaInvalid),
            2700 => Some(Self::RcNetworkUnreachable),
            2701 => Some(Self::RcNetworkProtocolInvalid),
            2702 => Some(Self::RcMsiInvalid),
            2703 => Some(Self::RcNetDnsResolutionFailed),
            2704 => Some(Self::RcNetConnectionFailed),
            2705 => Some(Self::RcNetWriteFailed),
            2706 => Some(Self::RcNetReadFailed),
            2707 => Some(Self::RcNetProtocolError),
            2708 => Some(Self::RcNetHttpRequestFailed),
            2709 => Some(Self::RcNetHttpHeaderNotFound),
            2710 => Some(Self::RcNetSocketCreateFailed),
            2711 => Some(Self::RcNetSendFailed),
            2712 => Some(Self::RcWebSocketFrameTooLarge),
            2713 => Some(Self::RcHttpHeaderLimitExceeded),
            2714 => Some(Self::RcPortParseError),
            2715 => Some(Self::RcRequestBodyTooLarge),
            2716 => Some(Self::RcSocketReceiveQueueFull),
            2800 => Some(Self::RcDrmInitFailed),
            2801 => Some(Self::RcDrmDecryptFailed),
            2802 => Some(Self::RcDrmIntegrityFailed),
            2803 => Some(Self::RcDrmLicenseInvalid),
            2804 => Some(Self::RcDrmPackUnsupported),
            2805 => Some(Self::RcDrmSectionNotFound),
            2806 => Some(Self::RcDrmRegionNotFound),
            2900 => Some(Self::RcWmiParseError),
            2901 => Some(Self::RcWmiClassNotFound),
            2902 => Some(Self::RcWmiObjectNotFound),
            2903 => Some(Self::RcTelemetryRanking),
            3000 => Some(Self::SehException),
            3001 => Some(Self::VeHandlerUnhandled),
            3002 => Some(Self::RcCrashRecoveryError),
            3100 => Some(Self::RcInvalidParameter),
            3102 => Some(Self::Halted),
            3103 => Some(Self::RcSignalHandlerError),
            3200 => Some(Self::RcOutOfMemory),
            3201 => Some(Self::RcOutOfMemoryHint),
            3300 => Some(Self::RcLockPoisoned),
            _ => None,
        }
    }

    pub const fn name(self) -> &'static str {
        match self {
            Self::Success => "SUCCESS",
            Self::RcCliInvalid => "RC_CLI_INVALID",
            Self::RcGeExists => "RC_GE_EXISTS",
            Self::RcGeNotFound => "RC_GE_NOT_FOUND",
            Self::RcIo => "RC_IO",
            Self::RcRunnerSpawnFailed => "RC_RUNNER_SPAWN_FAILED",
            Self::RcRunnerProtocolInvalid => "RC_RUNNER_PROTOCOL_INVALID",
            Self::RcTraceEnvMismatch => "RC_TRACE_ENV_MISMATCH",
            Self::RcCompareMismatch => "RC_COMPARE_MISMATCH",
            Self::RcDiagnosticsExportFailed => "RC_DIAGNOSTICS_EXPORT_FAILED",
            Self::RcHelperPermissionDenied => "RC_HELPER_PERMISSION_DENIED",
            Self::RcEntitlementAuditFailed => "RC_ENTITLEMENT_AUDIT_FAILED",
            Self::RcEntitlementValidationError => "RC_ENTITLEMENT_VALIDATION_ERROR",
            Self::RcFsPathInvalid => "RC_FS_PATH_INVALID",
            Self::RcFsAlreadyExists => "RC_FS_ALREADY_EXISTS",
            Self::RcFsNotFound => "RC_FS_NOT_FOUND",
            Self::RcFsReservedName => "RC_FS_RESERVED_NAME",
            Self::RcFsPathTooLong => "RC_FS_PATH_TOO_LONG",
            Self::RcFsSharingViolation => "RC_FS_SHARING_VIOLATION",
            Self::RcFsLockViolation => "RC_FS_LOCK_VIOLATION",
            Self::RcFsSandboxEscape => "RC_FS_SANDBOX_ESCAPE",
            Self::RcSandboxPathViolation => "RC_SANDBOX_PATH_VIOLATION",
            Self::RcRegistryNotFound => "RC_REGISTRY_NOT_FOUND",
            Self::RcWin32InvalidHandle => "RC_WIN32_INVALID_HANDLE",
            Self::RcWin32Timeout => "RC_WIN32_TIMEOUT",
            Self::RcComClassNotRegistered => "RC_COM_CLASS_NOT_REGISTERED",
            Self::RcMemoryAccessViolation => "RC_MEMORY_ACCESS_VIOLATION",
            Self::RcPipeBusy => "RC_PIPE_BUSY",
            Self::RcWin32NotOwner => "RC_WIN32_NOT_OWNER",
            Self::RcComObjectError => "RC_COM_OBJECT_ERROR",
            Self::RcHandleStaleOrInvalid => "RC_HANDLE_STALE_OR_INVALID",
            Self::RcPeParseInvalid => "RC_PE_PARSE_INVALID",
            Self::RcImportMissing => "RC_IMPORT_MISSING",
            Self::RcUnimplInsn => "RC_UNIMPL_INSN",
            Self::RcD3dFeatureUnsupported => "RC_D3D_FEATURE_UNSUPPORTED",
            Self::RcAnticheatDriverDetected => "RC_ANTICHEAT_DRIVER_DETECTED",
            Self::RcTlsCertRejected => "RC_TLS_CERT_REJECTED",
            Self::RcMsiCustomActionServiceBlocked => "RC_MSI_CUSTOM_ACTION_SERVICE_BLOCKED",
            Self::RcTlsValidationFailed => "RC_TLS_VALIDATION_FAILED",
            Self::RcBufferLimitExceeded => "RC_BUFFER_LIMIT_EXCEEDED",
            Self::RcInvalidGuestEnum => "RC_INVALID_GUEST_ENUM",
            Self::RcParserTruncation => "RC_PARSER_TRUNCATION",
            Self::RcUnsupportedPlatform => "RC_UNSUPPORTED_PLATFORM",
            Self::RcTlsCertificatePinMismatch => "RC_TLS_CERTIFICATE_PIN_MISMATCH",
            Self::RcUnsupportedPlatformApi => "RC_UNSUPPORTED_PLATFORM_API",
            Self::RcParserTruncated => "RC_PARSER_TRUNCATED",
            Self::RcJitCompilationError => "RC_JIT_COMPILATION_ERROR",
            Self::RcExecutableMemoryExhausted => "RC_EXECUTABLE_MEMORY_EXHAUSTED",
            Self::RcGuestPointerOutOfRange => "RC_GUEST_POINTER_OUT_OF_RANGE",
            Self::RcGuestStringInvalid => "RC_GUEST_STRING_INVALID",
            Self::RcInputUnsupported => "RC_INPUT_UNSUPPORTED",
            Self::RcDxilInvalid => "RC_DXIL_INVALID",
            Self::RcDxilBindingAmbiguous => "RC_DXIL_BINDING_AMBIGUOUS",
            Self::RcCacheCorrupt => "RC_CACHE_CORRUPT",
            Self::RcD3dInvalidState => "RC_D3D_INVALID_STATE",
            Self::RcD3d9NotSupported => "RC_D3D9_NOT_SUPPORTED",
            Self::RcVulkanNotSupported => "RC_VULKAN_NOT_SUPPORTED",
            Self::RcOpenGlNotSupported => "RC_OPENGL_NOT_SUPPORTED",
            Self::RcAudioUnsupported => "RC_AUDIO_UNSUPPORTED",
            Self::RcAudioBufferSizeMismatch => "RC_AUDIO_BUFFER_SIZE_MISMATCH",
            Self::RcWinsockWouldBlock => "RC_WINSOCK_WOULD_BLOCK",
            Self::RcDnsNotFound => "RC_DNS_NOT_FOUND",
            Self::RcCryptoInvalid => "RC_CRYPTO_INVALID",
            Self::RcDotnetUnsupported => "RC_DOTNET_UNSUPPORTED",
            Self::RcSteamUpdateFailed => "RC_STEAM_UPDATE_FAILED",
            Self::RcMediaInvalid => "RC_MEDIA_INVALID",
            Self::RcNetworkUnreachable => "RC_NETWORK_UNREACHABLE",
            Self::RcNetworkProtocolInvalid => "RC_NETWORK_PROTOCOL_INVALID",
            Self::RcMsiInvalid => "RC_MSI_INVALID",
            Self::RcInvalidState => "RC_INVALID_STATE",
            Self::RcNotFound => "RC_NOT_FOUND",
            Self::RcNetDnsResolutionFailed => "RC_NET_DNS_RESOLUTION_FAILED",
            Self::RcNetConnectionFailed => "RC_NET_CONNECTION_FAILED",
            Self::RcNetWriteFailed => "RC_NET_WRITE_FAILED",
            Self::RcNetReadFailed => "RC_NET_READ_FAILED",
            Self::RcNetProtocolError => "RC_NET_PROTOCOL_ERROR",
            Self::RcNetHttpRequestFailed => "RC_NET_HTTP_REQUEST_FAILED",
            Self::RcNetHttpHeaderNotFound => "RC_NET_HTTP_HEADER_NOT_FOUND",
            Self::RcNetSocketCreateFailed => "RC_NET_SOCKET_CREATE_FAILED",
            Self::RcNetSendFailed => "RC_NET_SEND_FAILED",
            Self::RcWebSocketFrameTooLarge => "RC_WEBSOCKET_FRAME_TOO_LARGE",
            Self::RcHttpHeaderLimitExceeded => "RC_HTTP_HEADER_LIMIT_EXCEEDED",
            Self::RcPortParseError => "RC_PORT_PARSE_ERROR",
            Self::RcRequestBodyTooLarge => "RC_REQUEST_BODY_TOO_LARGE",
            Self::RcSocketReceiveQueueFull => "RC_SOCKET_RECEIVE_QUEUE_FULL",
            Self::RcDrmInitFailed => "RC_DRM_INIT_FAILED",
            Self::RcDrmDecryptFailed => "RC_DRM_DECRYPT_FAILED",
            Self::RcDrmIntegrityFailed => "RC_DRM_INTEGRITY_FAILED",
            Self::RcDrmLicenseInvalid => "RC_DRM_LICENSE_INVALID",
            Self::RcDrmPackUnsupported => "RC_DRM_PACK_UNSUPPORTED",
            Self::RcDrmSectionNotFound => "RC_DRM_SECTION_NOT_FOUND",
            Self::RcDrmRegionNotFound => "RC_DRM_REGION_NOT_FOUND",
            Self::RcWmiParseError => "RC_WMI_PARSE_ERROR",
            Self::RcWmiClassNotFound => "RC_WMI_CLASS_NOT_FOUND",
            Self::RcWmiObjectNotFound => "RC_WMI_OBJECT_NOT_FOUND",
            Self::RcTelemetryRanking => "RC_TELEMETRY_RANKING",
            Self::SehException => "SEH_EXCEPTION",
            Self::VeHandlerUnhandled => "VE_HANDLER_UNHANDLED",
            Self::RcCrashRecoveryError => "RC_CRASH_RECOVERY_ERROR",
            Self::RcInvalidParameter => "RC_INVALID_PARAMETER",
            Self::Halted => "HALTED",
            Self::RcSignalHandlerError => "RC_SIGNAL_HANDLER_ERROR",
            Self::RcOutOfMemory => "RC_OUT_OF_MEMORY",
            Self::RcOutOfMemoryHint => "RC_OUT_OF_MEMORY_HINT",
            Self::RcJitCodeAllocFailed => "RC_JIT_CODE_ALLOC_FAILED",
            Self::RcLockPoisoned => "RC_LOCK_POISONED",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn reason_code_values_are_stable() {
        // These values must never change — they are part of the stable API.
        assert_eq!(ReasonCode::Success as u32, 0);
        assert_eq!(ReasonCode::RcIo as u32, 1003);
        assert_eq!(ReasonCode::RcPeParseInvalid as u32, 2000);
        assert_eq!(ReasonCode::RcTlsCertRejected as u32, 2005);
        assert_eq!(ReasonCode::RcJitCodeAllocFailed as u32, 2010);
        assert_eq!(ReasonCode::RcOutOfMemory as u32, 3200);
        assert_eq!(ReasonCode::RcTlsValidationFailed as u32, 2007);
        assert_eq!(ReasonCode::RcBufferLimitExceeded as u32, 2008);
        assert_eq!(ReasonCode::RcInvalidGuestEnum as u32, 2009);
        assert_eq!(ReasonCode::RcWebSocketFrameTooLarge as u32, 2712);
        assert_eq!(ReasonCode::RcHttpHeaderLimitExceeded as u32, 2713);
        assert_eq!(ReasonCode::RcTlsCertificatePinMismatch as u32, 2013);
        assert_eq!(ReasonCode::RcUnsupportedPlatformApi as u32, 2014);
        assert_eq!(ReasonCode::RcParserTruncated as u32, 2015);
        assert_eq!(ReasonCode::RcJitCompilationError as u32, 2016);
        assert_eq!(ReasonCode::RcExecutableMemoryExhausted as u32, 2017);
        assert_eq!(ReasonCode::RcGuestPointerOutOfRange as u32, 2018);
        assert_eq!(ReasonCode::RcGuestStringInvalid as u32, 2019);
        assert_eq!(ReasonCode::RcSocketReceiveQueueFull as u32, 2716);
        assert_eq!(ReasonCode::RcRequestBodyTooLarge as u32, 2715);
        assert_eq!(ReasonCode::RcSignalHandlerError as u32, 3103);
        assert_eq!(ReasonCode::RcComObjectError as u32, 1305);
        assert_eq!(ReasonCode::RcHandleStaleOrInvalid as u32, 1306);
        assert_eq!(ReasonCode::RcSandboxPathViolation as u32, 1108);
        assert_eq!(ReasonCode::RcEntitlementValidationError as u32, 1011);
        assert_eq!(ReasonCode::RcCrashRecoveryError as u32, 3002);
    }

    #[test]
    fn reason_code_values_are_unique() {
        // Collect every ReasonCode discriminant and verify no two share the same value.
        let codes: Vec<(ReasonCode, u32)> = vec![
            (ReasonCode::Success, 0),
            (ReasonCode::RcCliInvalid, 1000),
            (ReasonCode::RcGeExists, 1001),
            (ReasonCode::RcGeNotFound, 1002),
            (ReasonCode::RcIo, 1003),
            (ReasonCode::RcRunnerSpawnFailed, 1004),
            (ReasonCode::RcRunnerProtocolInvalid, 1005),
            (ReasonCode::RcTraceEnvMismatch, 1006),
            (ReasonCode::RcCompareMismatch, 1007),
            (ReasonCode::RcDiagnosticsExportFailed, 1008),
            (ReasonCode::RcHelperPermissionDenied, 1009),
            (ReasonCode::RcEntitlementAuditFailed, 1010),
            (ReasonCode::RcEntitlementValidationError, 1011),
            (ReasonCode::RcFsPathInvalid, 1100),
            (ReasonCode::RcFsAlreadyExists, 1101),
            (ReasonCode::RcFsNotFound, 1102),
            (ReasonCode::RcFsReservedName, 1103),
            (ReasonCode::RcFsPathTooLong, 1104),
            (ReasonCode::RcFsSharingViolation, 1105),
            (ReasonCode::RcFsLockViolation, 1106),
            (ReasonCode::RcFsSandboxEscape, 1107),
            (ReasonCode::RcSandboxPathViolation, 1108),
            (ReasonCode::RcRegistryNotFound, 1200),
            (ReasonCode::RcWin32InvalidHandle, 1300),
            (ReasonCode::RcWin32Timeout, 1301),
            (ReasonCode::RcComClassNotRegistered, 1302),
            (ReasonCode::RcMemoryAccessViolation, 1303),
            (ReasonCode::RcPipeBusy, 1304),
            (ReasonCode::RcWin32NotOwner, 1310),
            (ReasonCode::RcComObjectError, 1305),
            (ReasonCode::RcHandleStaleOrInvalid, 1306),
            (ReasonCode::RcPeParseInvalid, 2000),
            (ReasonCode::RcImportMissing, 2001),
            (ReasonCode::RcUnimplInsn, 2002),
            (ReasonCode::RcD3dFeatureUnsupported, 2003),
            (ReasonCode::RcAnticheatDriverDetected, 2004),
            (ReasonCode::RcTlsCertRejected, 2005),
            (ReasonCode::RcMsiCustomActionServiceBlocked, 2006),
            (ReasonCode::RcTlsValidationFailed, 2007),
            (ReasonCode::RcBufferLimitExceeded, 2008),
            (ReasonCode::RcInvalidGuestEnum, 2009),
            (ReasonCode::RcJitCodeAllocFailed, 2010),
            (ReasonCode::RcParserTruncation, 2011),
            (ReasonCode::RcUnsupportedPlatform, 2012),
            (ReasonCode::RcTlsCertificatePinMismatch, 2013),
            (ReasonCode::RcUnsupportedPlatformApi, 2014),
            (ReasonCode::RcParserTruncated, 2015),
            (ReasonCode::RcJitCompilationError, 2016),
            (ReasonCode::RcExecutableMemoryExhausted, 2017),
            (ReasonCode::RcGuestPointerOutOfRange, 2018),
            (ReasonCode::RcGuestStringInvalid, 2019),
            (ReasonCode::RcInputUnsupported, 2100),
            (ReasonCode::RcDxilInvalid, 2101),
            (ReasonCode::RcDxilBindingAmbiguous, 2102),
            (ReasonCode::RcCacheCorrupt, 2103),
            (ReasonCode::RcD3dInvalidState, 2104),
            (ReasonCode::RcD3d9NotSupported, 2105),
            (ReasonCode::RcVulkanNotSupported, 2106),
            (ReasonCode::RcOpenGlNotSupported, 2107),
            (ReasonCode::RcInvalidState, 2108),
            (ReasonCode::RcNotFound, 2109),
            (ReasonCode::RcAudioUnsupported, 2200),
            (ReasonCode::RcAudioBufferSizeMismatch, 2201),
            (ReasonCode::RcWinsockWouldBlock, 2300),
            (ReasonCode::RcDnsNotFound, 2301),
            (ReasonCode::RcCryptoInvalid, 2302),
            (ReasonCode::RcDotnetUnsupported, 2400),
            (ReasonCode::RcSteamUpdateFailed, 2500),
            (ReasonCode::RcMediaInvalid, 2600),
            (ReasonCode::RcNetworkUnreachable, 2700),
            (ReasonCode::RcNetworkProtocolInvalid, 2701),
            (ReasonCode::RcMsiInvalid, 2702),
            (ReasonCode::RcNetDnsResolutionFailed, 2703),
            (ReasonCode::RcNetConnectionFailed, 2704),
            (ReasonCode::RcNetWriteFailed, 2705),
            (ReasonCode::RcNetReadFailed, 2706),
            (ReasonCode::RcNetProtocolError, 2707),
            (ReasonCode::RcNetHttpRequestFailed, 2708),
            (ReasonCode::RcNetHttpHeaderNotFound, 2709),
            (ReasonCode::RcNetSocketCreateFailed, 2710),
            (ReasonCode::RcNetSendFailed, 2711),
            (ReasonCode::RcWebSocketFrameTooLarge, 2712),
            (ReasonCode::RcHttpHeaderLimitExceeded, 2713),
            (ReasonCode::RcPortParseError, 2714),
            (ReasonCode::RcRequestBodyTooLarge, 2715),
            (ReasonCode::RcSocketReceiveQueueFull, 2716),
            (ReasonCode::RcDrmInitFailed, 2800),
            (ReasonCode::RcDrmDecryptFailed, 2801),
            (ReasonCode::RcDrmIntegrityFailed, 2802),
            (ReasonCode::RcDrmLicenseInvalid, 2803),
            (ReasonCode::RcDrmPackUnsupported, 2804),
            (ReasonCode::RcDrmSectionNotFound, 2805),
            (ReasonCode::RcDrmRegionNotFound, 2806),
            (ReasonCode::RcWmiParseError, 2900),
            (ReasonCode::RcWmiClassNotFound, 2901),
            (ReasonCode::RcWmiObjectNotFound, 2902),
            (ReasonCode::RcTelemetryRanking, 2903),
            (ReasonCode::SehException, 3000),
            (ReasonCode::VeHandlerUnhandled, 3001),
            (ReasonCode::RcCrashRecoveryError, 3002),
            (ReasonCode::Halted, 3102),
            (ReasonCode::RcSignalHandlerError, 3103),
            (ReasonCode::RcInvalidParameter, 3100),
            (ReasonCode::RcOutOfMemory, 3200),
            (ReasonCode::RcOutOfMemoryHint, 3201),
            (ReasonCode::RcLockPoisoned, 3300),
        ];

        let mut seen: HashSet<u32> = HashSet::new();
        for (code, expected_value) in &codes {
            let actual = *code as u32;
            assert_eq!(
                actual, *expected_value,
                "numeric value mismatch for {:?}: expected {}, got {}",
                code, expected_value, actual
            );
            assert!(
                seen.insert(*expected_value),
                "duplicate numeric value {} shared by {:?} and a previous code",
                expected_value,
                code
            );
        }
    }

    #[test]
    fn reason_code_roundtrip() {
        // Test all codes roundtrip through from_u32
        for code in [
            ReasonCode::Success,
            ReasonCode::RcCliInvalid,
            ReasonCode::RcIo,
            ReasonCode::RcPeParseInvalid,
            ReasonCode::RcTlsCertRejected,
            ReasonCode::RcNetworkUnreachable,
            ReasonCode::RcOutOfMemory,
            ReasonCode::RcTlsValidationFailed,
            ReasonCode::RcBufferLimitExceeded,
            ReasonCode::RcPortParseError,
            ReasonCode::RcLockPoisoned,
            ReasonCode::RcTlsCertificatePinMismatch,
            ReasonCode::RcUnsupportedPlatformApi,
            ReasonCode::RcParserTruncated,
            ReasonCode::RcJitCompilationError,
            ReasonCode::RcExecutableMemoryExhausted,
            ReasonCode::RcGuestPointerOutOfRange,
            ReasonCode::RcGuestStringInvalid,
            ReasonCode::RcSocketReceiveQueueFull,
            ReasonCode::RcRequestBodyTooLarge,
            ReasonCode::RcSignalHandlerError,
            ReasonCode::RcComObjectError,
            ReasonCode::RcHandleStaleOrInvalid,
            ReasonCode::RcSandboxPathViolation,
            ReasonCode::RcEntitlementValidationError,
            ReasonCode::RcCrashRecoveryError,
        ] {
            let value = code.as_u32();
            assert_eq!(
                ReasonCode::from_u32(value),
                Some(code),
                "roundtrip failed for {:?}",
                code
            );
        }
    }

    #[test]
    fn reason_code_names_are_nonempty() {
        // Enumerate all codes and check names
        for value in [
            0u32, 1000, 1001, 1002, 1003, 1011, 1100, 1101, 1108, 1300, 1305, 1306, 2000, 2001,
            2002, 2005, 2010, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2200, 2300, 2700, 2715,
            2716, 3000, 3001, 3002, 3100, 3103, 3200, 3300,
        ] {
            if let Some(code) = ReasonCode::from_u32(value) {
                assert!(!code.name().is_empty(), "name is empty for code {}", value);
            }
        }
    }
}
